{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moorgate.secretName" . }}
  labels:
    {{- include "moorgate.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  FLEET_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  FLEET_CSRF_SECRET: {{ .Values.secrets.csrfSecret | quote }}
  FLEET_CA_PASSPHRASE: {{ .Values.secrets.caPassphrase | quote }}
  FLEET_VAULT_PASSPHRASE: {{ .Values.secrets.vaultPassphrase | quote }}
  FLEET_BACKUP_PASSPHRASE: {{ .Values.secrets.backupPassphrase | quote }}
  FLEET_AUDIT_HMAC_KEY: {{ .Values.secrets.auditHmacKey | quote }}
  FLEET_ANSIBLE_RUNNER_TOKEN: {{ .Values.secrets.ansibleRunnerToken | quote }}
  FLEET_RECORDING_KEY: {{ .Values.secrets.recordingKey | quote }}
  FLEET_DATABASE_URL: {{ include "moorgate.databaseUrl" . | quote }}
  {{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  {{- end }}
{{- end }}
