//go:build ignore

// gendocs embeds the curated Fleet Terminal documentation into docs_generated.go
// so the assistant's search_docs tool can retrieve it without any runtime file
// access. The repository docs/ directory is the single source of truth; run
//
//	go generate ./internal/assistant/
//
// (or `make assistant-docs`) after editing docs to refresh the embedded copy.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// The curated, user-facing set — must match frontend/scripts/build-help.mjs so the
// assistant and the in-app help cover the same documentation.
var curated = []struct{ File, Title string }{
	{"installation.md", "Installation"},
	{"user-guide.md", "User Guide"},
	{"admin-guide.md", "Administration"},
	{"operations.md", "Operations"},
	{"host-enrollment-guide.md", "Host Enrollment"},
	{"certificate-lifecycle.md", "Certificate Lifecycle"},
	{"api.md", "API Reference"},
	{"automation.md", "Automation (SDK & CLI)"},
	{"security-guide.md", "Security"},
	{"deployment.md", "Deployment"},
	{"internet-exposure.md", "Internet Exposure"},
}

func main() {
	docsDir := flag.String("docs", "../../../docs", "path to the repository docs/ directory")
	out := flag.String("out", "docs_generated.go", "output Go file")
	flag.Parse()

	var b strings.Builder
	b.WriteString("// Code generated by gendocs.go; DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: go generate ./internal/assistant/\n")
	b.WriteString("// Source of truth: the repository docs/ directory.\n\n")
	b.WriteString("package assistant\n\n")
	b.WriteString("var embeddedDocs = []embeddedDoc{\n")

	n := 0
	for _, d := range curated {
		data, err := os.ReadFile(filepath.Join(*docsDir, d.File))
		if err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: skipping %s: %v\n", d.File, err)
			continue
		}
		slug := strings.TrimSuffix(d.File, ".md")
		fmt.Fprintf(&b, "\t{Slug: %s, Title: %s, Markdown: %s},\n",
			strconv.Quote(slug), strconv.Quote(d.Title), strconv.Quote(string(data)))
		n++
	}
	b.WriteString("}\n")

	if n == 0 {
		fmt.Fprintf(os.Stderr, "gendocs: no docs found under %s — refusing to emit an empty index\n", *docsDir)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: write %s: %v\n", *out, err)
		os.Exit(1)
	}
	fmt.Printf("gendocs: embedded %d docs -> %s\n", n, *out)
}
