import { useState } from "react";
import {
  Alert, Box, Button, Chip, Paper, Stack, Table, TableBody, TableCell, TableHead,
  TableRow, Tooltip, Typography,
} from "@mui/material";
import BackupIcon from "@mui/icons-material/Backup";
import RefreshIcon from "@mui/icons-material/Refresh";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { formatDateTime } from "../../lib/datetime";
import {
  keyBackupStatus, createKeyBackup, inspectKeyBackup, type KeyBackupItem,
} from "../../api/imaging";

// The imaging state the database backup cannot hold.
//
// Machines, rollouts, users, sessions and the audit log are rows in Postgres and
// are covered by the encrypted database backup. These three are files, and one of
// them cannot be regenerated by anything: lose the signing key and no machine
// already deployed can ever be updated again — not "until we re-key", ever,
// because each verifies against a certificate baked into its own image.
//
// The archive is written on the host and stays there. There is no download, and
// that is the point: a signing key fetchable over HTTP is a signing key whose
// custody is whoever holds a session cookie.

function bytes(n: number): string {
  if (!n) return "—";
  if (n >= 1e9) return (n / 1e9).toFixed(2) + " GB";
  if (n >= 1e6) return (n / 1e6).toFixed(1) + " MB";
  if (n >= 1e3) return (n / 1e3).toFixed(1) + " kB";
  return `${n} B`;
}

export function KeysTab({ canProvision, setMsg }: {
  canProvision: boolean;
  setMsg: (text: string, kind?: "success" | "error") => void;
}) {
  const qc = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ["imaging-keys"], queryFn: keyBackupStatus });
  const [inspected, setInspected] = useState<string[] | null>(null);
  const refresh = () => void qc.invalidateQueries({ queryKey: ["imaging-keys"] });

  const backup = useMutation({
    mutationFn: createKeyBackup,
    onSuccess: (r) => {
      setMsg(`Wrote ${r.name} (${bytes(r.size)}) on the server. sha256 ${r.sha256.slice(0, 16)}…`);
      refresh();
    },
    onError: (e) => setMsg(errText(e, "Could not write the backup."), "error"),
  });

  const inspect = useMutation({
    mutationFn: (name: string) => inspectKeyBackup(name),
    onSuccess: (r) => setInspected(r.entries),
    onError: (e) => setMsg(errText(e, "Could not read that archive."), "error"),
  });

  const items = data?.items ?? [];
  const backups = data?.backups ?? [];

  return (
    <Box>
      <Stack direction="row" alignItems="center" sx={{ mb: 2 }}>
        <Box sx={{ flexGrow: 1 }}>
          <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
            Imaging keys and configuration
          </Typography>
          <Typography variant="body2" color="text.secondary">
            The imaging state that is <strong>not</strong> in the database, and so is not
            in the database backup. Everything else — machines, rollouts, users, the audit
            log — is a row in Postgres and is covered there.
          </Typography>
        </Box>
        <Tooltip title="Refresh"><Button onClick={refresh} startIcon={<RefreshIcon />}>Refresh</Button></Tooltip>
        <Button
          variant="contained" startIcon={<BackupIcon />} sx={{ ml: 1 }}
          disabled={!canProvision || backup.isPending || !data?.scriptPresent}
          onClick={() => backup.mutate()}
        >
          {backup.isPending ? "Writing…" : "Back up now"}
        </Button>
      </Stack>

      {data && !data.haveSigningKey && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          <strong>There is no signing key on this server.</strong> Either this deployment
          has never built an update bundle, or the key is missing — and if it ever had one,
          a backup taken now would not contain it. Machines already deployed accept only
          bundles signed by the original; find that backup rather than making a new key.
        </Alert>
      )}

      {data && !data.scriptPresent && (
        <Alert severity="info" sx={{ mb: 2 }}>
          The backup script is not in this checkout, so nothing can be written from here.
        </Alert>
      )}

      <Alert severity="info" sx={{ mb: 2 }}>
        The archive is written <strong>on the server</strong> and stays there — there is no
        download, deliberately. A signing key that can be fetched over HTTP is one whose
        custody is whoever holds a session cookie. Copy it off with <code>scp</code>, as a
        decision rather than a click, and store it as you would the key itself.
      </Alert>

      <Paper variant="outlined" sx={{ mb: 3, overflowX: "auto" }}>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>What</TableCell>
              <TableCell>Why it matters</TableCell>
              <TableCell align="right">Size</TableCell>
              <TableCell>Present</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {items.map((i: KeyBackupItem) => (
              <TableRow key={i.path}>
                <TableCell><code>{i.path}</code></TableCell>
                <TableCell>
                  <Typography variant="body2" color="text.secondary">{i.why}</Typography>
                </TableCell>
                <TableCell align="right">{i.present ? bytes(i.size) : "—"}</TableCell>
                <TableCell>
                  {i.present
                    ? <Chip size="small" color="success" variant="outlined" label="yes" />
                    : <Chip size="small" variant="outlined" label="no" />}
                </TableCell>
              </TableRow>
            ))}
            {items.length === 0 && (
              <TableRow><TableCell colSpan={4}>
                <Typography variant="body2" color="text.secondary" sx={{ py: 1 }}>
                  {isLoading ? "Loading…" : "Nothing reported — is the builder running?"}
                </Typography>
              </TableCell></TableRow>
            )}
          </TableBody>
        </Table>
      </Paper>

      <Typography variant="subtitle2" sx={{ mb: 1 }}>
        Backups on the server{data?.dir ? <> — <code>{data.dir}</code></> : null}
      </Typography>
      <Paper variant="outlined" sx={{ overflowX: "auto" }}>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Archive</TableCell>
              <TableCell align="right">Size</TableCell>
              <TableCell>Written</TableCell>
              <TableCell align="right" />
            </TableRow>
          </TableHead>
          <TableBody>
            {backups.map((b) => (
              <TableRow key={b.name} hover>
                <TableCell><code>{b.name}</code></TableCell>
                <TableCell align="right">{bytes(b.size)}</TableCell>
                <TableCell>{formatDateTime(b.created)}</TableCell>
                <TableCell align="right">
                  <Button size="small" disabled={inspect.isPending}
                          onClick={() => inspect.mutate(b.name)}>
                    What's in it
                  </Button>
                </TableCell>
              </TableRow>
            ))}
            {backups.length === 0 && (
              <TableRow><TableCell colSpan={4}>
                <Typography variant="body2" color="text.secondary" sx={{ py: 1 }}>
                  {isLoading ? "Loading…" : "No backups yet. The signing key is not reproducible from anything — take one."}
                </Typography>
              </TableCell></TableRow>
            )}
          </TableBody>
        </Table>
      </Paper>

      {inspected && (
        <Paper variant="outlined" sx={{ mt: 2, p: 2 }}>
          <Stack direction="row" alignItems="center" sx={{ mb: 1 }}>
            <Typography variant="subtitle2" sx={{ flexGrow: 1 }}>Archive contents</Typography>
            <Button size="small" onClick={() => setInspected(null)}>Close</Button>
          </Stack>
          {/* Names only. Reading the contents out would be the download this page
              deliberately does not have. */}
          <Box component="pre" sx={{ m: 0, fontSize: 13, fontFamily: "monospace", overflowX: "auto" }}>
            {inspected.join("\n")}
          </Box>
        </Paper>
      )}

      <Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 2 }}>
        This is half of a restore. The database backup is the other half — see the
        disaster-recovery guide. Restoring is done with
        {" "}<code>scripts/imaging/imaging-keys-backup.sh restore</code> on the host rather
        than from here: the moment you need it is the moment this server is not running,
        and a button that only works when you do not need it is not a recovery procedure.
      </Typography>
    </Box>
  );
}

function errText(e: unknown, fallback: string): string {
  const d = (e as { response?: { data?: { error?: string } } })?.response?.data?.error;
  return d ? `${fallback} ${d}` : fallback;
}
