-- RDP session recordings. Unlike SSH recordings (asciicast, written by the backend
-- and tied to ssh_sessions), RDP recordings are Guacamole-protocol streams written
-- by the guacd sidecar to a shared volume; the backend only stores metadata and
-- serves the file back for replay via Guacamole.SessionRecording. The row id is the
-- guacd recording file name, so it is generated by the application before the guacd
-- handshake (no DB default).
CREATE TABLE IF NOT EXISTS rdp_recordings (
    id          UUID PRIMARY KEY,
    host_id     UUID REFERENCES hosts(id) ON DELETE SET NULL,
    user_id     UUID REFERENCES users(id) ON DELETE SET NULL,
    hostname    TEXT NOT NULL,
    fleet_user  TEXT NOT NULL DEFAULT '',
    rdp_user    TEXT NOT NULL DEFAULT '',
    format      TEXT NOT NULL DEFAULT 'guacamole',
    path        TEXT NOT NULL,
    size_bytes  BIGINT NOT NULL DEFAULT 0,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    status      TEXT NOT NULL DEFAULT 'active',
    client_ip   TEXT NOT NULL DEFAULT '',
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_rdp_recordings_started ON rdp_recordings(started_at DESC);
