apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provenance.fullname" . }}-config
  labels:
    {{- include "provenance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  PROV_REDIS_URL: {{ include "provenance.redisUrl" . | quote }}
  {{- if .Values.ansibleRunner.enabled }}
  PROV_ANSIBLE_RUNNER_URL: {{ printf "http://%s:8000" (include "provenance.ansibleRunner.fullname" .) | quote }}
  {{- end }}
  {{- if .Values.grypeScanner.enabled }}
  PROV_GRYPE_SCANNER_URL: {{ printf "http://%s:8000" (include "provenance.grypeScanner.fullname" .) | quote }}
  {{- end }}
