{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "provenance.secretName" . }}
  labels:
    {{- include "provenance.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  PROV_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  PROV_CSRF_SECRET: {{ .Values.secrets.csrfSecret | quote }}
  PROV_CA_PASSPHRASE: {{ .Values.secrets.caPassphrase | quote }}
  PROV_VAULT_PASSPHRASE: {{ .Values.secrets.vaultPassphrase | quote }}
  PROV_BACKUP_PASSPHRASE: {{ .Values.secrets.backupPassphrase | quote }}
  PROV_AUDIT_HMAC_KEY: {{ .Values.secrets.auditHmacKey | quote }}
  PROV_ANSIBLE_RUNNER_TOKEN: {{ .Values.secrets.ansibleRunnerToken | quote }}
  PROV_RECORDING_KEY: {{ .Values.secrets.recordingKey | quote }}
  PROV_DATABASE_URL: {{ include "provenance.databaseUrl" . | quote }}
  {{- if .Values.postgres.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  {{- end }}
{{- end }}
