#!/bin/sh
# Render dnsmasq config from environment, then run it.
#
# Modes:
#   MODE=dhcp   -> standalone DHCP: this server also hands out IP leases (default)
#   MODE=proxy  -> proxyDHCP: coexists with an existing DHCP server
set -eu

MODE="${MODE:-dhcp}"
TFTP_ROOT="/srv/tftp"
CONF="/etc/dnsmasq.runtime.conf"
: "${SERVER_IP:?Set SERVER_IP to the provisioning server IP address}"
# Required, not optional. This container runs with host networking, so an
# unset interface would make dnsmasq answer DHCP on *every* network the host
# is attached to — including the office LAN. Confining it is the whole point.
: "${INTERFACE:?Set INTERFACE to the provisioning NIC — DHCP/TFTP are confined to it}"

# A dedicated provisioning NIC usually has no IP: nothing on that segment hands
# one out, because this server is what's meant to. dnsmasq cannot serve DHCP on
# an address-less interface, so bring it up and give it SERVER_IP here. Runtime
# only — a reboot reverts it and this re-applies on start, which keeps the host's
# permanent network configuration untouched. Existing addresses are left alone.
if [ -n "${SERVER_PREFIXLEN:-}" ]; then
    ip link set "$INTERFACE" up 2>/dev/null || true
    if ip -4 addr show dev "$INTERFACE" 2>/dev/null | grep -q "inet ${SERVER_IP}/"; then
        echo "[net] ${INTERFACE} already has ${SERVER_IP}"
    elif ip addr add "${SERVER_IP}/${SERVER_PREFIXLEN}" dev "$INTERFACE" 2>/dev/null; then
        echo "[net] assigned ${SERVER_IP}/${SERVER_PREFIXLEN} to ${INTERFACE}"
    else
        echo "[net] WARNING: could not assign ${SERVER_IP}/${SERVER_PREFIXLEN} to ${INTERFACE}" >&2
    fi
fi

{
    echo "# Generated by entrypoint.sh"
    # DHCP/proxyDHCP + TFTP only — with host networking, dnsmasq would
    # otherwise also run a DNS server on the host's port 53 (and collide
    # with systemd-resolved or any local resolver).
    echo "port=0"
    echo "log-dhcp"
    echo "enable-tftp"
    echo "tftp-root=${TFTP_ROOT}"
    # A whole switch powering on at once all fetch the iPXE binary in the same
    # few seconds. dnsmasq's default cap is 50 concurrent TFTP transfers; past
    # that clients fail to boot rather than queueing. Only the ~100 KB
    # bootloader goes over TFTP — the image itself is HTTP — so raising this is
    # cheap.
    echo "tftp-max=${TFTP_MAX:-200}"
    echo "dhcp-lease-max=${DHCP_LEASE_MAX:-500}"
    # interface + bind-interfaces: bind sockets to this NIC alone rather than
    # the wildcard address, so nothing leaks onto the host's other networks.
    echo "interface=${INTERFACE}"
    echo "bind-interfaces"
    echo "except-interface=lo"
    echo "no-hosts"
    echo "no-resolv"
    echo "dhcp-no-override"

    # Tag iPXE clients (they send DHCP option 175) and UEFI clients by
    # architecture. The client tells us what it is in DHCP option 93:
    #   0  = x86 BIOS        7, 9 = x86-64 UEFI        11 = arm64 UEFI
    # Without the arm64 tag an aarch64 machine is handed undionly.kpxe, an x86
    # BIOS binary, and dies at the firmware with nothing useful on screen.
    echo "dhcp-match=set:ipxe,175"
    echo "dhcp-match=set:efi64,option:client-arch,7"
    echo "dhcp-match=set:efi64,option:client-arch,9"
    echo "dhcp-match=set:efiarm64,option:client-arch,11"

    if [ "$MODE" = "dhcp" ]; then
        : "${DHCP_RANGE_START:?Set DHCP_RANGE_START for MODE=dhcp}"
        : "${DHCP_RANGE_END:?Set DHCP_RANGE_END for MODE=dhcp}"
        echo "dhcp-authoritative"
        echo "dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},${DHCP_NETMASK:-255.255.255.0},${LEASE_TIME:-1h}"
        [ -n "${DHCP_ROUTER:-}" ] && echo "dhcp-option=3,${DHCP_ROUTER}"
        [ -n "${DHCP_DNS:-}" ] && echo "dhcp-option=6,${DHCP_DNS}"
        # Boot files by client type. Most specific first: dnsmasq takes the
        # first dhcp-boot whose tags all match, so the arm64 line has to come
        # before the untagged x86 fallback or arm64 machines never reach it.
        echo "dhcp-boot=tag:ipxe,http://${SERVER_IP}/boot.ipxe"
        echo "dhcp-boot=tag:!ipxe,tag:efiarm64,ipxe-arm64.efi"
        echo "dhcp-boot=tag:!ipxe,tag:efi64,ipxe.efi"
        echo "dhcp-boot=tag:!ipxe,tag:!efi64,tag:!efiarm64,undionly.kpxe"
    else
        : "${PROXY_SUBNET:?Set PROXY_SUBNET (e.g. 192.168.1.0) for MODE=proxy}"
        echo "dhcp-range=${PROXY_SUBNET},proxy"
        # proxyDHCP: hand PXE clients an iPXE binary, then iPXE fetches the script.
        echo "pxe-service=tag:!ipxe,x86PC,\"Network boot (BIOS)\",undionly.kpxe"
        echo "pxe-service=tag:!ipxe,BC_EFI,\"Network boot (UEFI)\",ipxe.efi"
        echo "pxe-service=tag:!ipxe,X86-64_EFI,\"Network boot (UEFI)\",ipxe.efi"
        echo "pxe-service=tag:!ipxe,ARM64_EFI,\"Network boot (arm64 UEFI)\",ipxe-arm64.efi"
        echo "dhcp-boot=tag:ipxe,http://${SERVER_IP}/boot.ipxe"
    fi
} > "$CONF"

echo "----- dnsmasq configuration (MODE=$MODE) -----"
cat "$CONF"
echo "----------------------------------------------"

exec dnsmasq -k -d -C "$CONF"
