// Build the in-app help bundle from the curated docs/ Markdown.
//
// Reads the allow-listed docs, splits each into searchable sections (by heading),
// rewrites inter-doc `./x.md#a` links to in-app `/help/x#a` routes, and emits a
// typed module the frontend imports. Runs automatically before `dev` and `build`
// (see package.json). The generated file is git-ignored — docs/ is the single
// source of truth.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = resolve(here, "../../docs");
const outFile = resolve(here, "../src/help/help-content.ts");

// Curated, user-facing set (excludes developer/DB-internals/emergency runbooks).
const DOCS = [
  { file: "installation.md", title: "Installation", category: "Getting started", order: 1 },
  { file: "user-guide.md", title: "User Guide", category: "Getting started", order: 2 },
  { file: "admin-guide.md", title: "Administration", category: "Administration", order: 3 },
  { file: "operations.md", title: "Operations", category: "Administration", order: 4 },
  { file: "host-enrollment-guide.md", title: "Host Enrollment", category: "Administration", order: 5 },
  { file: "certificate-lifecycle.md", title: "Certificate Lifecycle", category: "Administration", order: 6 },
  { file: "api.md", title: "API Reference", category: "Reference", order: 7 },
  { file: "security-guide.md", title: "Security", category: "Reference", order: 8 },
  { file: "deployment.md", title: "Deployment", category: "Reference", order: 9 },
  { file: "internet-exposure.md", title: "Internet Exposure", category: "Reference", order: 10 },
  { file: "CHANGELOG.md", title: "Changelog", category: "Reference", order: 11 },
];

// Must match the frontend heading-id function (src/help/HelpPage renderer) exactly,
// so search/TOC anchors line up with rendered heading ids.
function slugify(s) {
  return s
    .toLowerCase()
    .replace(/`/g, "")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

// Rewrite inter-doc links so they navigate within the in-app help.
function rewriteLinks(md, knownSlugs) {
  return md.replace(/\]\(\.\/([a-zA-Z0-9._-]+)\.md(#[^)]+)?\)/g, (m, name, hash) => {
    if (!knownSlugs.has(name)) return m; // link to a doc not in the help set: leave as-is
    return `](/help/${name}${hash || ""})`;
  });
}

function sections(md) {
  const out = [];
  let cur = null;
  for (const line of md.split("\n")) {
    const h = /^(#{1,6})\s+(.*)$/.exec(line);
    if (h) {
      if (cur) out.push(cur);
      const heading = h[2].replace(/[#*`]/g, "").trim();
      cur = { heading, level: h[1].length, anchor: slugify(heading), text: "" };
    } else if (cur) {
      cur.text += line + " ";
    }
  }
  if (cur) out.push(cur);
  return out.map((s) => ({ ...s, text: s.text.replace(/\s+/g, " ").trim().slice(0, 2000) }));
}

const knownSlugs = new Set(DOCS.map((d) => d.file.replace(/\.md$/, "")));
const docs = DOCS.map((d) => {
  const slug = d.file.replace(/\.md$/, "");
  let md;
  try {
    md = readFileSync(resolve(docsDir, d.file), "utf8");
  } catch {
    console.warn(`build-help: skipping missing ${d.file}`);
    return null;
  }
  md = rewriteLinks(md, knownSlugs);
  return { slug, title: d.title, category: d.category, order: d.order, markdown: md, sections: sections(md) };
}).filter(Boolean);

const banner = "// AUTO-GENERATED by scripts/build-help.mjs — do not edit. Edit docs/ instead.\n";
const types = `export interface HelpSection { heading: string; level: number; anchor: string; text: string; }
export interface HelpDoc { slug: string; title: string; category: string; order: number; markdown: string; sections: HelpSection[]; }
`;
const body = `export const helpDocs: HelpDoc[] = ${JSON.stringify(docs, null, 2)};\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + types + "\n" + body);
console.log(`build-help: wrote ${docs.length} docs, ${docs.reduce((n, d) => n + d.sections.length, 0)} sections -> src/help/help-content.ts`);
