package k8sbroker

import (
	"context"
	"os"
	"path/filepath"
	"strings"

	"github.com/kforbus3/provenance/backend/internal/store"
)

// headlampConfigPath is where the embedded Headlamp reads its cluster list.
// Empty disables the whole mechanism, which is the case for any deployment not
// running the kubernetes compose profile.
func headlampConfigPath() string { return os.Getenv("PROV_HEADLAMP_KUBECONFIG") }

// writeHeadlampClusters tells the embedded Headlamp which clusters exist.
//
// It needs this even though it holds no credential. A kubeconfig is how Headlamp
// learns a cluster's NAME and SERVER; without one it knows about nothing, and
// opening the console lands on "Something went wrong with cluster <name>" --
// which is what shipped, because "give it no token" was implemented as "give it
// no kubeconfig".
//
// Deliberately written with NO user and NO token. Headlamp then shows its own
// "Use a token" prompt, and each operator supplies the one Provenance minted for
// them. A shared token here would be less friction and would make every operator
// reach Provenance as the same identity, collapsing the audit log to one actor
// for the whole team -- which is the reason to embed a UI rather than link out.
//
// Best effort: a deployment without the kubernetes profile has nowhere to write
// this and does not want it, so a failure is logged by the caller, never fatal.
func writeHeadlampClusters(ctx context.Context, st interface {
	ListK8sClusters(context.Context) ([]store.K8sCluster, error)
}, publicURL string) error {
	path := headlampConfigPath()
	if path == "" {
		return nil
	}
	clusters, err := st.ListK8sClusters(ctx)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	// Written whole and replaced atomically: Headlamp may read this at any
	// moment, and a half-written kubeconfig is worse than a stale one.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(renderHeadlampConfig(publicURL, clusters)), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// renderHeadlampConfig builds the credential-free kubeconfig.
func renderHeadlampConfig(publicURL string, clusters []store.K8sCluster) string {
	base := strings.TrimSuffix(publicURL, "/")
	var b strings.Builder
	b.WriteString("# Generated by Provenance for the embedded Headlamp.\n")
	b.WriteString("# Servers only -- no user and no token, deliberately. Each operator\n")
	b.WriteString("# supplies their own, from Kubernetes -> Download kubeconfig.\n")
	b.WriteString("apiVersion: v1\nkind: Config\n")
	if len(clusters) == 0 {
		b.WriteString("clusters: []\ncontexts: []\nusers: []\n")
		return b.String()
	}
	b.WriteString("clusters:\n")
	for _, c := range clusters {
		b.WriteString("  - name: " + yamlStr(c.Name) + "\n    cluster:\n")
		b.WriteString("      server: " + yamlStr(base+"/api/v1/k8s/clusters/"+c.ID.String()+"/proxy") + "\n")
	}
	b.WriteString("contexts:\n")
	for _, c := range clusters {
		b.WriteString("  - name: " + yamlStr(c.Name) + "\n    context:\n")
		b.WriteString("      cluster: " + yamlStr(c.Name) + "\n")
		if ns := strings.TrimSpace(c.Namespace); ns != "" {
			b.WriteString("      namespace: " + yamlStr(ns) + "\n")
		}
	}
	b.WriteString("users: []\n")
	b.WriteString("current-context: " + yamlStr(clusters[0].Name) + "\n")
	return b.String()
}
