package k8sbroker

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/kforbus3/provenance/backend/internal/auth"
	"github.com/kforbus3/provenance/backend/internal/httpx"
	"github.com/kforbus3/provenance/backend/internal/store"
)

// kubeconfigScope confines the minted token to the Kubernetes broker.
//
// This is the reason a kubeconfig is safe to hand out at all. The file ends up
// on a laptop, in a Headlamp container, in somebody's dotfiles — and unscoped it
// would carry its owner's entire permission set with no MFA and no session
// behind it. Scoped, the worst a leaked kubeconfig can do is exactly what its
// owner could already do to the clusters, which is the risk the operator
// consciously took.
const kubeconfigScope = "/api/v1/k8s"

// kubeconfigTTL bounds the damage of a file nobody remembers copying.
//
// Deliberately finite: a credential that lives in a file and never expires is
// one nobody ever revokes, because nobody remembers it exists.
const kubeconfigTTL = 90 * 24 * time.Hour

// kubeconfig mints a scoped token for the caller and returns a kubeconfig that
// reaches every cluster they can see, through the broker.
//
// One request rather than "create a token" then "download a config", because the
// two are useless apart and splitting them means an operator can hold a token
// with no idea what to point it at.
//
// The token is returned exactly once, inside the file. Provenance stores only
// its hash, so a lost kubeconfig is regenerated rather than recovered.
func (h *handler) kubeconfig(w http.ResponseWriter, r *http.Request) {
	p := auth.MustPrincipal(r)
	if p == nil || p.UserID == uuid.Nil {
		httpx.WriteError(w, http.StatusUnauthorized, "not signed in")
		return
	}
	// A scoped token cannot mint another token: that would let a leaked
	// kubeconfig renew itself indefinitely and escape its own expiry.
	if p.TokenScope != "" {
		httpx.WriteError(w, http.StatusForbidden,
			"a scoped token cannot issue another one — sign in to download a kubeconfig")
		return
	}

	clusters, err := h.d.Store.ListK8sClusters(r.Context())
	if err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "could not list clusters")
		return
	}
	if len(clusters) == 0 {
		httpx.WriteError(w, http.StatusBadRequest,
			"no clusters are registered, so a kubeconfig would reach nothing")
		return
	}

	token, hash, prefix, err := auth.NewAPIToken()
	if err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "could not mint a token")
		return
	}
	expires := time.Now().Add(kubeconfigTTL)
	if _, err := h.d.Store.CreateScopedAPIToken(r.Context(), p.UserID,
		"kubeconfig for "+p.Username, hash, prefix, p.UserID, &expires, kubeconfigScope); err != nil {
		httpx.WriteError(w, http.StatusInternalServerError, "could not record the token")
		return
	}

	base := strings.TrimSuffix(h.d.Cfg.PublicURL, "/")
	body := renderKubeconfig(base, p.Username, token, clusters)

	h.audit(r, "k8s.kubeconfig", uuid.Nil, map[string]any{
		"clusters": len(clusters), "scope": kubeconfigScope,
		"expires": expires.Format(time.RFC3339), "prefix": prefix,
	})
	w.Header().Set("Content-Type", "application/yaml")
	w.Header().Set("Content-Disposition", `attachment; filename="provenance-kubeconfig.yaml"`)
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(body))
}

// renderKubeconfig writes the file by hand rather than through a YAML library.
//
// Every value here is either a UUID, a generated token or a cluster name, and
// names are quoted. A YAML round-trip would add a dependency and reorder keys
// for a document this small and this fixed.
func renderKubeconfig(base, username, token string, clusters []store.K8sCluster) string {
	var b strings.Builder
	b.WriteString("# Generated by Provenance. Every request below is brokered:\n")
	b.WriteString("# the cluster's own credential stays vaulted and never reaches this file,\n")
	b.WriteString("# and every call is recorded against " + username + ".\n")
	b.WriteString("#\n")
	b.WriteString("# This token is limited to " + kubeconfigScope + " and can do nothing else\n")
	b.WriteString("# in Provenance. It is still a credential: treat the file as one.\n")
	b.WriteString("apiVersion: v1\nkind: Config\n")

	b.WriteString("clusters:\n")
	for _, c := range clusters {
		b.WriteString("  - name: " + yamlStr(c.Name) + "\n")
		b.WriteString("    cluster:\n")
		b.WriteString("      server: " + yamlStr(fmt.Sprintf("%s/api/v1/k8s/clusters/%s/proxy", base, c.ID)) + "\n")
	}

	b.WriteString("users:\n")
	b.WriteString("  - name: " + yamlStr(username) + "\n")
	b.WriteString("    user:\n")
	b.WriteString("      token: " + yamlStr(token) + "\n")

	b.WriteString("contexts:\n")
	for _, c := range clusters {
		b.WriteString("  - name: " + yamlStr(c.Name) + "\n")
		b.WriteString("    context:\n")
		b.WriteString("      cluster: " + yamlStr(c.Name) + "\n")
		b.WriteString("      user: " + yamlStr(username) + "\n")
		if ns := strings.TrimSpace(c.Namespace); ns != "" {
			b.WriteString("      namespace: " + yamlStr(ns) + "\n")
		}
	}
	b.WriteString("current-context: " + yamlStr(clusters[0].Name) + "\n")
	return b.String()
}

// yamlStr double-quotes a scalar and escapes what that quoting makes special, so
// a cluster named `foo: bar` or `"x"` cannot break the document.
func yamlStr(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`)
	return `"` + r.Replace(s) + `"`
}
